user:
  outputs:
    default:
      account: GLAPRSA-YBC36152
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: DBT_DB
      password: dataengineertraining300K!
      retry_on_database_errors: true
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 6
      type: snowflake
      user: dionnedm29
      warehouse: COMPUTE_WH
  target: default
